title: 也许睡一觉会有灵感
email: zeyaprism@gmail.com
description: "1992*4##111" #> # this means to ignore newlines until "baseurl:"
  # Write an awesome description for your new site here. You can edit this
  # line in _config.yml. It will appear in your document head meta (for
  # Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "zeyap.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  zeyap

# Build settings
markdown: kramdown